In [1]:
# Imports
import numpy as np
import pandas as pd

# Q1:
    Write a function so that the columns of the output matrix are powers of the input vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
input_vector = np.random.randint(10, 100, size=10)
input_vector

array([94, 89, 29, 32, 15, 72, 62, 64, 72, 64])

In [3]:
powers = np.arange(input_vector.size - 1, -1, -1)
powers

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
output_vector = pow(input_vector, powers)
output_vector

array([572994802228616704,   3936588805702081,        17249876309,
               1073741824,             759375,           26873856,
                   238328,               4096,                 72,
                        1])

# Q2:
    Write a function to find moving average in an array over a window:
    Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
def moving_avg(arr, k):
    output = np.zeros((arr.size - k + 1))
    for i in range(output.size):
        output[i] = arr[i : i + k].mean()
    return output

test = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print(moving_avg(test, 3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [6]:
moving_avg(np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]), 4)

array([25., 35., 45., 55., 65., 75., 85.])